version: "2"

services:
  ## ==== HADOOP ====
  namenode:
    build: ./hadoop-namenode
    hostname: namenode
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "50070:50070"

  resourcemanager:
    build: ./hadoop-resourcemanager
    hostname: resourcemanager
    container_name: resourcemanager
    depends_on:
      - "namenode"
    links:
      - "namenode"
    env_file:
      - ./hadoop.env
    ports:
      - "58088:8088"

  historyserver:
    build: ./hadoop-historyserver
    hostname: historyserver
    container_name: historyserver
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    depends_on:
      - "namenode"
    links:
      - "namenode"
    env_file:
      - ./hadoop.env
    ports:
      - "58188:8188"

  nodemanager1:
    build: ./hadoop-nodemanager
    hostname: nodemanager1
    container_name: nodemanager1
    depends_on:
      - "namenode"
      - "resourcemanager"
    links:
      - "namenode"
      - "resourcemanager"
    env_file:
      - ./hadoop.env
    ports:
      - "58042:8042"

  datanode1:
    build: ./hadoop-datanode
    hostname: datanode1
    container_name: datanode1
    depends_on:
      - "namenode"
    links:
      - "namenode"
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    #environment:
    #  SERVICE_PRECONDITION: "namenode:50070"

  datanode2:
    build: ./hadoop-datanode
    hostname: datanode2
    container_name: datanode2
    depends_on:
      - "namenode"
    links:
      - "namenode"
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    #environment:
    #  SERVICE_PRECONDITION: "namenode:50070"

  datanode3:
    build: ./hadoop-datanode
    hostname: datanode3
    container_name: datanode3
    depends_on:
      - "namenode"
    links:
      - "namenode"
    volumes:
      - ./data/datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    #environment:
    #  SERVICE_PRECONDITION: "namenode:50070"

  filebrowser:
    #image: bde2020/hue
    image: bde2020/hdfs-filebrowser:3.11
    hostname: filebrowser
    container_name: filebrowser
    environment:
      - NAMENODE_HOST=namenode
    ports:
      - "8088:8088"

  ## ==== HIVE ====
  hive-server:
    build: ./hive
    hostname: hive-server
    container_name: hive-server
    depends_on:
      - "hive-metastore"
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    build: ./hive
    hostname: hive-metastore
    container_name: hive-metastore
    depends_on:
      - "namenode"
      - "datanode1"
      - "datanode2"
      - "datanode3"
      - "hive-postgresql"
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 hive-postgresql:5432"
    command: /usr/local/hive/bin/hive --service metastore
    ports:
      - "9083:9083"

  hive-postgresql:
    build: ./hive-postgresql
    hostname: hive-postgresql
    container_name: hive-postgresql

  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    ports:
      - "8080:8080"
